quarkus:
  datasource:
    db-kind: postgresql
    username: user
    password: password
    reactive:
      url: vertx-reactive:postgresql://localhost:5432/my_db
  hibernate-orm:
    database:
      generation:
        ~: update
